create database ToDoList;
create table "users" (id int generated by default as IDENTITY PRIMARY KEY,
		Login varchar(90),
		Password varchar(250))
-- create table Note(id int generated by default as identity primary key,
-- 		Name varchar(90),
-- 		Body varchar(300))
-- -- create table user_note(id int,
-- 		user_id int references "user"(id),
-- 		note_id int references Note(id))