create database ToDoList;
create table "users" (id int generated by default as IDENTITY PRIMARY KEY,
		Login varchar(90),
		Password varchar(250))
-- create table note(note_id int generated by default as identity primary key,
-- 		Name varchar(90),
-- 		Body varchar(300))
-- -- create table user_note(user_note_id int,
-- 		user_id int references "user"(id),
-- 		note_id int references note(id))
-- create table team(team_id int generated by default as identity,
-- 					team_name varchar(120),
-- 					team_description varchar(250))
-- create table project(project_id int generated by default as identity,
-- 					project_name varchar(120),
-- 					project_description varchar(250))
-- create table ToDoTask(TDTask_id int generated by default as identity,
-- 					 TDTask_name varchar(120),
-- 					 TDTask_description varchar(250),
-- 					 TDTask_status int,
-- 					 TDTask_deadline date
-- 					 чото ещё можно наверное)
-- create table friend(friend_id int generated by default as identity,
-- 					friend_name varchar(120))
-- create table DENGI(subs_id int generated by default as identity,
-- здесь типа короче user_id но я бля нахуй забыл чо писал там в скриптах)
-- create table "access"(access_id int generated by default as identity, 
-- user_id int reference "user"(id), 
-- TDTas_id int reference ToDoTask(TDTask_id),
-- project_id int reference project(project_id),
-- team_id int reference team(team_id))